export const players = [
    {
        name: "Mohamed Salah",
        nationality: "EGY",
        birth: "15 Jun 1992",
        position: "Forward",
        age: 32,
        player_id: 48,
        number: 11,
        foot: "Left",
        value: 53,
        photo: "https://media.api-sports.io/football/players/306.png",
        rating: 7.55,
        height: "175cm",
        goals: "2 ⚽",
        assists: "1 ↪️",
        scoringFreq: 87,
        shots: 3.5,
        targetShots: 2.5,
        available: "✅"
    },
    {
        name: "Darwin Núñez",
        nationality: "URU",
        birth: "24 Jun 1999",
        position: "Forward",
        age: 25,
        player_id: 49,
        number: 9,
        foot: "Right",
        value: 64,
        photo: "https://media.api-sports.io/football/players/51617.png",
        rating: 7.12,
        height: "188cm",
        available: "✅"
    },
    {
        name: "Luis Díaz",
        nationality: "COL",
        birth: "13 Jan 1997",
        position: "Forward",
        age: 27,
        player_id: 50,
        number: 7,
        foot: "Right",
        value: 81,
        photo: "https://media.api-sports.io/football/players/2489.png",
        rating: 7.23,
        height: "178cm",
        goals: "1 ⚽",
        assists: "1 ↪️",
        scoringFreq: 162,
        shots: 3,
        targetShots: 1.0,
        available: "✅"
    },
    {
        name: "Cody Gakpo",
        nationality: "NED",
        birth: "7 May 1999",
        position: "Forward",
        age: 25,
        player_id: 51,
        number: 18,
        foot: "Right",
        value: 53,
        photo: "https://media.api-sports.io/football/players/247.png",
        rating: 7.24,
        height: "193cm",
        shots: 0.5,
        yellow: "1 🟨",
        available: "✅"
    },
    {
        name: "Diogo Jota",
        nationality: "POR",
        birth: "4 Dec 1996",
        position: "Forward",
        age: 27,
        player_id: 52,
        number: 20,
        foot: "Right",
        value: 49,
        photo: "https://media.api-sports.io/football/players/2678.png",
        rating: 7.13,
        height: "178cm",
        goals: "1 ⚽",
        assists: "1 ↪️",
        scoringFreq: 151,
        shots: 3.5,
        targetShots: 0.5,
        available: "✅"
    },
    {
        name: "Alexis Mac Allister",
        nationality: "ARG",
        birth: "24 Dec 1998",
        position: "Midfielder",
        age: 25,
        player_id: 42,
        number: 10,
        foot: "Right",
        value: 82,
        photo: "https://media.api-sports.io/football/players/6716.png",
        rating: 7.19,
        height: "176cm",
        shots: 1,
        available: "✅"
    },
    {
        name: "Dominik Szoboszlai",
        nationality: "HUN",
        birth: "25 Oct 2000",
        position: "Midfielder",
        age: 23,
        player_id: 43,
        number: 8,
        foot: "Right",
        value: 68,
        photo: "https://media.api-sports.io/football/players/1096.png",
        rating: 7.32,
        height: "187cm",
        shots: 2.0,
        yellow: "1 🟨",
        available: "✅"
    },
    {
        name: "Harvey Elliott",
        nationality: "ENG",
        birth: "4 Apr 2003",
        position: "Midfielder",
        age: 21,
        player_id: 44,
        number: 19,
        foot: "Left",
        value: 36,
        photo: "https://media.api-sports.io/football/players/19035.png",
        rating: 7.40,
        height: "170cm",
        available: "✅"
    },
    {
        name: "Ryan Gravenberch",
        nationality: "NED",
        birth: "16 May 2002",
        position: "Midfielder",
        age: 22,
        player_id: 45,
        number: 38,
        foot: "Right",
        value: 38,
        photo: "https://media.api-sports.io/football/players/542.png",
        rating: 6.95,
        height: "190cm",
        yellow: "1 🟨",
        available: "✅"
    },
    {
        name: "Wataru Endo",
        nationality: "JPN",
        birth: "9 Feb 1993",
        position: "Midfielder",
        age: 31,
        player_id: 46,
        number: 3,
        foot: "Right",
        value: 11.9,
        photo: "https://media.api-sports.io/football/players/8500.png",
        rating: 6.91,
        height: "178cm",
        available: "✅"
    },
    {
        name: "Curtis Jones",
        nationality: "ENG",
        birth: "30 Jan 2001",
        position: "Midfielder",
        age: 23,
        player_id: 47,
        number: 17,
        foot: "Right",
        value: 33,
        photo: "https://media.api-sports.io/football/players/293.png",
        rating: 6.93,
        height: "185cm",
        available: "✅"
    },
    {
        name: "Trent Alexander-Arnold",
        nationality: "ENG",
        birth: "7 Oct 1998",
        position: "Defender",
        age: 25,
        player_id: 34,
        number: 66,
        foot: "Right",
        value: 72,
        photo: "https://media.api-sports.io/football/players/283.png",
        rating: 7.40,
        height: "180cm",
        shots: 1.5,
        available: "✅"
    },
    {
        name: "Virgil van Dijk",
        nationality: "NED",
        birth: "8 Jul 1991",
        position: "Defender",
        age: 33,
        player_id: 35,
        number: 4,
        foot: "Right",
        value: 31,
        photo: "https://media.api-sports.io/football/players/290.png",
        rating: 7.32,
        height: "193cm",
        shots: 0.5,
        targetShots: 0.5,
        available: "✅"
    },
    {
        name: "Andrew Robertson",
        nationality: "SCO",
        birth: "11 Mar 1994",
        position: "Defender",
        age: 30,
        player_id: 36,
        number: 26,
        foot: "Left",
        value: 32,
        photo: "https://media.api-sports.io/football/players/289.png",
        rating: 7.30,
        height: "178cm",
        shots: 1,
        targetShots: 1.0,
        available: "✅"
    },
    {
        name: "Ibrahima Konaté",
        nationality: "FRA",
        birth: "25 MAY 1999",
        position: "Defender",
        age: 30,
        player_id: 37,
        number: 5,
        foot: "Right",
        value: 46,
        photo: "https://media.api-sports.io/football/players/1145.png",
        rating: 7.30,
        height: "195cm",
        shots: 1,
        targetShots: 0.5,
        available: "✅"
    },
    {
        name: "Konstantinos Tsimikas",
        nationality: "GRE",
        birth: "12 May 1996",
        position: "Defender",
        age: 28,
        player_id: 38,
        number: 21,
        foot: "Left",
        value: 21,
        photo: "https://media.api-sports.io/football/players/1600.png",
        rating: 7.03,
        height: "178cm",
        available: "✅"
    },
    {
        name: "Joe Gomez",
        nationality: "ENG",
        birth: "23 May 1997",
        position: "Defender",
        age: 27,
        player_id: 39,
        number: 2,
        foot: "Right",
        value: 27,
        photo: "https://media.api-sports.io/football/players/284.png",
        rating: 6.92,
        height: "188cm",
        available: "✅"
    },
    {
        name: "Conor Bradley",
        nationality: "NIR",
        birth: "9 Jul 2003",
        position: "Defender",
        age: 21,
        player_id: 40,
        number: 84,
        foot: "Right",
        value: 16.5,
        photo: "https://media.api-sports.io/football/players/180317.png",
        rating: 7.15,
        height: "181cm",
        shots: 1,
        targetShots: 0.5,
        available: "✅"
    },
    {
        name: "Jarell Quansah",
        nationality: "ENG",
        birth: "29 Jan 2003",
        position: "Defender",
        age: 21,
        player_id: 41,
        number: 78,
        foot: "Right",
        value: 23,
        photo: "https://media.api-sports.io/football/players/158698.png",
        rating: 7.02,
        height: "190cm",
        available: "✅"
    },
    {
        name: "Caoimhin Kelleher",
        nationality: "IRL",
        birth: "23 Nov 1998",
        position: "Goalkeeper",
        age: 25,
        player_id: 32,
        number: 62,
        foot: "Right",
        value: 18,
        photo: "https://media.api-sports.io/football/players/281.png",
        rating: 7.05,
        height: "188cm",
        available: "✅"
    },
    {
        name: "Alisson",
        nationality: "BRA",
        birth: "2 Oct 1992",
        position: "Goalkeeper",
        age: 31,
        player_id: 33,
        number: 1,
        foot: "Right",
        value: 31,
        photo: "https://media.api-sports.io/football/players/280.png",
        rating: 7.06,
        height: "191cm",
        available: "✅"
    }
]